repos:
- repo: local
  hooks:
#  - id: dead
#    name: dead
#    entry: dead
#    args:
#      - "--exclude"
#      - "test_data/test_content.py|^deprecated/" # regex separate by "|"
#    language: system
#    pass_filenames: false
#    # types: [python]

  - id: black
    name: black
    language: system
    entry: black .
    types: [python]

  - id: codespell
    name: codespell
    language: system
    entry: codespell
#    args:
#      - "src/"
#      - "tests/"
#      - "*.md"
#      - "*.py"
    # pass_filenames: false
    types_or: [python, markdown]
    exclude: ^test_data/

  - id: ruff
    name: ruff
    language: system
    entry: ruff
    args:
      # Tell ruff to fix sorting of imports
      - "--fix"
      - "--format=github"
      - "--target-version=py311"
      - "."
    # types: [python]
    pass_filenames: false

 # https://jaredkhan.com/blog/mypy-pre-commit
  - id: mypy
    name: mypy
    # entry: python -c "import sys; print(sys.argv)"
    entry: mypy
    args: ["--check-untyped-defs"]
    language: python
    language_version: python3.13
    require_serial: true
    # To be able to exclude properly
    pass_filenames: true
    types: [python]
    # args: ["--config-file=pyproject.toml"]
    # exclude: .*(shape|compareshape)\.py$
    # Print the number of files as a sanity-check
    verbose: true

  - id: pytest
    name: pytest
    language: system
    entry: pytest
    args:
      # - "--durations=10"
      - "--exitfirst"
    pass_filenames: false
